import { PrismaClient,EstadoEquipo,Rol,EstadoReserva,EstadoPrestamo,Severidad,EstadoIncidencia,TipoMantenimiento,EstadoMantenimiento } from '@prisma/client'; import * as bcrypt from 'bcrypt'; const p=new PrismaClient();
async function main(){
 const users=[['Administrador','SIGET','admin@siget.local',Rol.ADMINISTRADOR,process.env.SEED_ADMIN_PASSWORD||'Cambiar123!'],['Encargado','Inventario','inventario@siget.local',Rol.ENCARGADO_INVENTARIO,process.env.SEED_INVENTARIO_PASSWORD||'Cambiar123!'],['Usuario','Demo','usuario@siget.local',Rol.USUARIO,process.env.SEED_USUARIO_PASSWORD||'Cambiar123!'],['Tecnico','Soporte','tecnico@siget.local',Rol.TECNICO,process.env.SEED_TECNICO_PASSWORD||'Cambiar123!']] as const;
 const um:any={}; for(const [nombre,apellido,correo,rol,pw] of users){um[rol]=await p.usuario.upsert({where:{correo},update:{},create:{nombre,apellido,correo,rol,passwordHash:await bcrypt.hash(pw,12)}})}
 const catNames=['Laptop','Computadora de escritorio','Proyector','Tablet','Cámara','Monitor','Impresora']; const cats:any[]=[]; for(const nombre of catNames)cats.push(await p.categoria.upsert({where:{nombre},update:{activo:true},create:{nombre,descripcion:`Categoría ${nombre}`}}));
 const estados=[...Array(12).fill(EstadoEquipo.DISPONIBLE),...Array(2).fill(EstadoEquipo.RESERVADO),...Array(2).fill(EstadoEquipo.PRESTADO),...Array(3).fill(EstadoEquipo.MANTENIMIENTO),EstadoEquipo.BAJA]; const equipos:any[]=[]; for(let i=0;i<20;i++){equipos.push(await p.equipo.upsert({where:{codigoInventario:`SIGET-${String(i+1).padStart(3,'0')}`},update:{},create:{codigoInventario:`SIGET-${String(i+1).padStart(3,'0')}`,nombre:`Equipo tecnológico ${i+1}`,marca:['Dell','HP','Lenovo','Epson','Samsung'][i%5],modelo:`M-${100+i}`,numeroSerie:`SN-SIGET-${1000+i}`,categoriaId:cats[i%cats.length].id,ubicacion:i%2?'Laboratorio':'Bodega TI',estado:estados[i],fechaAdquisicion:new Date('2025-01-15')}}))}
 if(await p.reserva.count()===0){await p.reserva.create({data:{usuarioId:um[Rol.USUARIO].id,equipoId:equipos[12].id,fechaInicio:new Date(Date.now()+86400000),fechaFin:new Date(Date.now()+3*86400000),motivo:'Presentación institucional',estado:EstadoReserva.APROBADA,aprobadoPorId:um[Rol.ENCARGADO_INVENTARIO].id}}); await p.reserva.create({data:{usuarioId:um[Rol.USUARIO].id,equipoId:equipos[0].id,fechaInicio:new Date(Date.now()+5*86400000),fechaFin:new Date(Date.now()+6*86400000),motivo:'Trabajo académico'}})}
 if(await p.prestamo.count()===0){await p.prestamo.create({data:{usuarioId:um[Rol.USUARIO].id,equipoId:equipos[14].id,entregadoPorId:um[Rol.ENCARGADO_INVENTARIO].id,fechaPrestamo:new Date(Date.now()-86400000),fechaLimite:new Date(Date.now()+2*86400000),estado:EstadoPrestamo.ACTIVO}}); await p.prestamo.create({data:{usuarioId:um[Rol.USUARIO].id,equipoId:equipos[15].id,entregadoPorId:um[Rol.ENCARGADO_INVENTARIO].id,fechaPrestamo:new Date(Date.now()-5*86400000),fechaLimite:new Date(Date.now()-2*86400000),estado:EstadoPrestamo.ATRASADO}})}
 if(await p.incidencia.count()===0)await p.incidencia.create({data:{equipoId:equipos[16].id,usuarioReportaId:um[Rol.USUARIO].id,titulo:'Equipo no enciende',descripcion:'No muestra señales de energía',severidad:Severidad.ALTA,estado:EstadoIncidencia.EN_REVISION}});
 if(await p.mantenimiento.count()===0)await p.mantenimiento.create({data:{equipoId:equipos[16].id,tecnicoId:um[Rol.TECNICO].id,tipo:TipoMantenimiento.CORRECTIVO,descripcion:'Diagnóstico de fuente y placa',fechaInicio:new Date(),estado:EstadoMantenimiento.EN_PROCESO}});
}
main().finally(()=>p.$disconnect());
