sonar.projectKey=siget
sonar.projectName=SIGET
sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,backend/src/generated/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
